version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: shippler_nginx
    links:
      - phpfpm
    volumes:
      - ./appdata:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    working_dir: /var/www/html
  phpfpm:
    build: ./phpfpm
    container_name: shippler_phpfpm
    links:
      - db
    volumes:
      - ./appdata:/var/www/html
    working_dir: /var/www/html
    environment:
      TERM: xterm
  node:
    build: ./node
    container_name: shippler_node
    links:
      - phpfpm
    volumes:
      - ./appdata:/var/www/html
    working_dir: /var/www/html
  db:
    image: mysql:5.7
    container_name: shippler_db
    environment:
      MYSQL_ROOT_PASSWORD: shippler
      MYSQL_DATABASE: shippler
      MYSQL_USER: shippler
      MYSQL_PASSWORD: shippler
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33081:3306"
volumes:
  dbdata:
    driver: local
